const cards = [
    {
        id: 1,
        bottom1: ["money_plus", "money_plus", "money_plus", "triquetra_5"],
        bottom2: ["letter", "letter"],
        top: ["letter", "letter", "money_plus"],
        type: "yellow",
    },
    {
        id: 2,
        bottom1: ["money_plus", "money_plus", "money_plus", "triquetra_5"],
        bottom2: ["axe", "axe"],
        top: ["axe", "axe", "money_plus", "triquetra"],
        type: "red",
    },
    {
        id: 3,
        bottom1: ["money_plus", "money_plus", "money_plus", "triquetra_5"],
        bottom2: ["church", "church"],
        top: ["church", "church", "money_plus", "triquetra"],
        type: "blue",
    },
    {
        id: 4,
        bottom1: ["money_plus", "money_plus", "money_plus", "triquetra_5"],
        bottom2: ["letter", "letter"],
        top: ["letter", "letter", "triquetra"],
        type: "yellow",
    },
    {
        id: 5,
        bottom1: ["money_plus", "money_plus", "triquetra_5"],
        bottom2: ["axe", "axe"],
        top: ["axe", "axe", "triquetra"],
        type: "red",
    },
    {
        id: 6,
        bottom1: ["money_plus", "money_plus", "money_plus", "triquetra_5"],
        bottom2: ["church", "church"],
        top: ["church", "church", "triquetra"],
        type: "blue",
    },
    {
        id: 7,
        bottom1: ["money_plus", "money_plus", "triquetra_5"],
        bottom2: ["letter", "letter"],
        top: ["letter", "money_plus", "triquetra"],
        type: "yellow",
    },
    {
        id: 8,
        bottom1: ["money_plus", "money_plus", "triquetra_5"],
        bottom2: ["axe", "axe"],
        top: ["axe", "money_plus", "triquetra"],
        type: "red",
    },
    {
        id: 9,
        bottom1: ["money_plus", "money_plus", "triquetra_5"],
        bottom2: ["church", "church"],
        top: ["church", "money_plus", "triquetra"],
        type: "blue",
    },
    {
        id: 10,
        bottom1: ["money_plus", "money_plus", "triquetra_5"],
        bottom2: ["letter", "letter"],
        top: ["money_plus", "money_plus", "triquetra"],
        type: "yellow",
    },
    {
        id: 11,
        bottom1: ["money_plus", "money_plus", "triquetra_5"],
        bottom2: ["axe", "axe"],
        top: ["money_plus", "money_plus", "triquetra"],
        type: "red",
    },
    {
        id: 12,
        bottom1: ["money_plus", "money_plus", "triquetra_5"],
        bottom2: ["church", "church"],
        top: ["money_plus", "money_plus", "triquetra"],
        type: "blue",
    },
    {
        id: 13,
        bottom1: ["money_plus", "money_plus", "triquetra_5"],
        bottom2: ["money_minus", "viking_shield"],
        top: ["money_plus", "triquetra"],
        type: "gray",
    },
    {
        id: 14,
        bottom1: ["money_plus", "triquetra_5"],
        bottom2: ["letter", "letter", "letter"],
        top: ["triquetra"],
        type: "yellow",
    },
    {
        id: 15,
        bottom1: ["money_plus", "triquetra_5"],
        bottom2: ["axe", "axe", "axe"],
        top: ["triquetra"],
        type: "red",
    },
    {
        id: 16,
        bottom1: ["money_plus", "triquetra_5"],
        bottom2: ["church", "church", "church"],
        top: ["triquetra"],
        type: "blue",
    },
    {
        id: 17,
        bottom1: ["money_plus", "triquetra_5"],
        bottom2: ["letter", "letter", "letter"],
        top: ["money_minus", "triquetra"],
        type: "yellow",
    },
    {
        id: 18,
        bottom1: ["money_plus", "triquetra_5"],
        bottom2: ["axe", "axe", "axe"],
        top: ["money_minus", "triquetra"],
        type: "red",
    },
    {
        id: 19,
        bottom1: ["money_plus", "triquetra_5"],
        bottom2: ["church", "church", "church"],
        top: ["money_minus", "triquetra"],
        type: "blue",
    },
    {
        id: 20,
        bottom1: ["money_plus", "money_plus", "triquetra_5"],
        bottom2: [],
        top: ["triquetra"],
        type: "gray",
    },
    {
        id: 21,
        bottom1: ["money_plus", "money_plus", "triquetra_5"],
        bottom2: [],
        top: ["money_minus", "triquetra"],
        type: "gray",
    },
    {
        id: 22,
        bottom1: ["money_plus", "money_plus", "triquetra_5"],
        bottom2: [],
        top: ["money_minus", "money_minus", "triquetra"],
        type: "gray",
    },
    {
        id: 23,
        bottom1: ["money_plus", "triquetra_5"],
        bottom2: ["letter", "letter", "letter"],
        top: ["money_minus", "money_minus", "triquetra"],
        type: "yellow",
    },
    {
        id: 24,
        bottom1: ["money_plus", "triquetra_5"],
        bottom2: ["axe", "axe", "axe"],
        top: ["money_minus", "money_minus", "triquetra"],
        type: "red",
    },
    {
        id: 25,
        bottom1: ["money_plus", "triquetra_5"],
        bottom2: ["church", "church", "church"],
        top: ["money_minus", "money_minus", "triquetra"],
        type: "blue",
    },
];

export default cards;
